rg_name             = "cmaz-9m9bm0bv-mod3-rg"
location            = "eastus"
storageaccount_name = "cmaz9m9bm0bvsa"
vnet_name           = "cmaz-9m9bm0bv-mod3-vnet"
subnet1_name        = "frontend"
subnet2_name        = "backend"
student_email       = "ritik_kumar@epam.com"
